NO_ACTIONS = 0
NO_AVAILABITY = 1
DUPLICATED = 2
COLLAPSED_INVENTORY = 4
ARTIFICIAL_SHIP = 5

TRAINING = 0
TESTING_INSTANCE = 1
TESTING_BUFFER_INSTANCES = 4
TESTING_RANDOM_INSTANCES = 2
GENERATING_INSTANCES = 3